### ISSUE TITLE
文档更正

### ISSUE THREAD

**Issue by wangyiidii** [xuchengsheng/spring-reading#15]
如图，接口 `ConfigurableBeanFactory` 是继承了 `HierarchicalBeanFactory` 和 `SingletonBeanRegistry`。

<img width="1073" alt="image" src="https://github.com/xuchengsheng/spring-reading/assets/32561537/64f61d39-82c6-4b27-80c7-f55ee907dd3a">

**Comment by xuchengsheng** [comment]
已解决
